version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SECRET
      - DB
      - PORT
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-network

  db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: ksfzbheh
      POSTGRES_PASSWORD: AOvRLG7R4Ipc1aqxNkJoGC2NfyZailfM
      POSTGRES_DB: ksfzbheh
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
